#!/bin/bash

echo "🚀 Testing AccidentAlert Application Locally"
echo "============================================"

# Test with Docker Compose
echo "📦 Starting application with Docker Compose..."
echo "Run this command to test locally:"
echo ""
echo "docker-compose up --build"
echo ""
echo "Then access:"
echo "🌐 Frontend: http://localhost:3000"
echo "🔧 API Documentation: http://localhost:8000/docs"
echo "📊 Health Check: http://localhost:8000/health"
echo ""
echo "To stop: Press Ctrl+C and run 'docker-compose down'"
echo ""
echo "============================================"
echo "🎯 Alternative: Test Backend API Only"
echo "============================================"
echo ""
echo "cd backend"
echo "python3 -m venv venv"
echo "source venv/bin/activate"
echo "pip install -r requirements.txt"
echo "python main.py"
echo ""
echo "Then visit: http://localhost:8000/docs"